---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: default
  labels:
    k8s-app: backend
spec:
  ports:
  - name: tcp-80-80-nhbqg
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    k8s-app: backend
  type: LoadBalancer
  loadBalancerIP: 40.76.201.228